name_vpc: Masterui1
cidr: 10.0.0.0/16
region: eu-west-1
env: develop
subnet_info:  
  - { name: "publicAZ1", net: "10.0.1.0/24", az: "eu-west-1a", type: "public" }
  - { name: "publicAZ2", net: "10.0.2.0/24", az: "eu-west-1b", type: "public" }
  - { name: "publicAZ3", net: "10.0.3.0/24", az: "eu-west-1c", type: "public" }
  - { name: "privateAZ1", net: "10.0.4.0/24", az: "eu-west-1a", type: "private" }
  - { name: "privateAZ2", net: "10.0.5.0/24", az: "eu-west-1b", type: "private" }
  - { name: "privateAZ3", net: "10.0.6.0/24", az: "eu-west-1c", type: "private" }

