apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-08-24T07:02:33Z
  labels:
    kops.k8s.io/cluster: k8ui1.almatronics.es
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: t2.micro
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:975195398054:targetgroup/tg-kops/faf013fe7af37d1c
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c